main = ".open-next/worker.js"
name = "taskw-docs"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[routes]]
pattern = "taskw.nkaewam.dev"
custom_domain = true
